export enum Category {
  ENTERTAINMENT = "DIVERSION",
  EXTRAS = "OTROS",
  FASHION = "MODA",
  FOOD = "COMIDA",
  HEALTH = "SALUD",
  HOME = "CASA",
  LOANS = "PRESTAMOS",
  PROFITABILITY = "PROFITABILIDAD",
  SALARY = "SALARIO",
  TAXES = "IMPUESTOS",
  TECHNOLOGY = "TECNOLOGIA",
  TRANSPORTATION = "TRANSPORTE"
  }
  
  export enum Type {
    EXPENSE = "EXPENSE",
    INCOME = "INCOME",
  }

