resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 7s
        slow-call-rate-threshold: 50

    instances:
      bills:
        base-config: default #NOMBRE DE LA CONFIGURACION CREADA ARRIBA

  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      bills:
        base-config: default