name: Deploy Spring Boot App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy a servidor vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/admin_jb_1/springboot-app/C1-registro-de-gastos-e-ingresos
            git pull origin main
            mvn clean package -DskipTests
            systemctl restart mi-servicio-java  # Reemplaza con el nombre real del servicio

